// src/lib/nova.ts — Nova's app backend: database + user accounts.
//
// Generated by Nova. Safe to read, not worth editing: it is a typed wrapper
// around the runtime injected into index.html.
//
//   import { db, auth, connectors, useCollection, useUser } from './lib/nova'
//
//   const { rows, loading, reload } = useCollection<Task>('tasks')
//   await db.create<Task>('tasks', { title: 'Ship it', done: false })
//   const user = useUser()
//
// Rows created while a user is signed in belong to that user; pass
// { mine: true } to a query to read only theirs.
import { useCallback, useEffect, useState } from 'react'

export interface NovaRecord<T> {
  id: string
  data: T
  created_at: string
  updated_at: string
}

export interface NovaUser {
  id: string
  email: string
  name?: string
  /**
   * What this account is allowed to be, set by the app's owner in NOVA.
   *
   * USE IT TO HIDE THINGS, NEVER TO PERMIT THEM. The server has already decided
   * what this user may read and write, from the rules on the project — by the
   * time you can read this field, that decision is made. Showing an "Admin"
   * tab only when role === 'admin' is good manners; RELYING on that check is
   * not security, because this value arrived over the network to a browser the
   * user controls.
   */
  role?: string
}

export interface QueryOptions {
  /** Max rows to return. Default 50. */
  limit?: number
  offset?: number
  /** Newest first by default. */
  order?: 'asc' | 'desc'
  /** Only rows belonging to the signed-in user. */
  mine?: boolean
  /** Match one field inside the row's data. */
  whereKey?: string
  whereValue?: string | number | boolean
  /** Match several fields at once, ANDed: { status: 'open', assignee: 'ana' } */
  where?: Record<string, string | number | boolean>
  /** Sort by a field inside the row's data, e.g. 'dueDate'. Rows without it go last. */
  sort?: string
  /** Case-insensitive substring match across the whole record. */
  search?: string
}

type Backend = any
function backend(): Backend {
  const b = (window as any).novaDB
  if (!b) {
    throw new Error(
      'Nova backend unavailable. index.html is missing the novaDB runtime.'
    )
  }
  return b
}

export const db = {
  /** Insert a row and return it. */
  async create<T>(collection: string, data: T): Promise<NovaRecord<T>> {
    return await backend().add(collection, data)
  },
  /** Read rows, filtered and sorted by the server. */
  async list<T>(
    collection: string,
    options: QueryOptions = {}
  ): Promise<{ total: number; records: NovaRecord<T>[] }> {
    const res = await backend().query(collection, options)
    return { total: res?.total ?? 0, records: res?.records ?? [] }
  },
  /** One row by id, or null if it does not exist or is not yours. */
  async get<T>(collection: string, id: string): Promise<NovaRecord<T> | null> {
    // Asks the server for the ONE row. This used to list 200 records and
    // search them here, which could not find row 201 and shipped a page of
    // other people's data to answer a question about one of them.
    return await backend().one(collection, id)
  },
  /** Merge changes into a row. */
  async update<T>(
    collection: string,
    id: string,
    data: Partial<T>
  ): Promise<NovaRecord<T>> {
    return await backend().edit(collection, id, data)
  },
  /** Delete a row. */
  async remove(collection: string, id: string): Promise<void> {
    await backend().drop(collection, id)
  },
}

export interface NovaFile {
  id: string
  name: string
  contentType: string
  /** Bytes. */
  size: number
  /** Null when uploaded by a signed-out visitor. */
  ownerId: string | null
  /** Absolute — drop it straight into an <img src> or an <a href>. */
  url: string
  createdAt: string
}

/**
 * File uploads.
 *
 * The returned `url` needs no token, which is what makes it usable in an
 * <img src>. It is unguessable rather than private: treat it like a share
 * link, because that is what it is.
 */
export const storage = {
  /** Upload a File from an <input type="file"> and get its URL back. */
  async upload(file: File): Promise<NovaFile> {
    return await backend().files.upload(file)
  },
  /** This app's files, newest first, with usage against the quota. */
  async list(options: { limit?: number; offset?: number; mine?: boolean } = {}): Promise<{
    total: number
    files: NovaFile[]
    usedBytes: number
    quotaBytes: number
  }> {
    return await backend().files.list(options)
  },
  async remove(id: string): Promise<void> {
    await backend().files.remove(id)
  },
}

export const auth = {
  async signup(email: string, password: string, name?: string): Promise<NovaUser> {
    return await backend().auth.signup(email, password, name)
  },
  async login(email: string, password: string): Promise<NovaUser> {
    return await backend().auth.login(email, password)
  },
  /**
   * One-click sign-in through Nova — no configuration, no OAuth keys.
   *
   * Opens a popup and resolves once the visitor has signed in. The consent
   * screen says Nova rather than this app's brand: that is the trade for
   * requiring nothing of the app's owner. Email and password remain available
   * for anyone who wants an unbranded flow.
   *
   * MUST be called directly from a click handler, or the browser blocks the
   * popup.
   */
  async signInWithNova(): Promise<NovaUser> {
    return await backend().auth.withNova()
  },
  /** The signed-in user, or null. */
  async me(): Promise<NovaUser | null> {
    const user = await backend().auth.user()
    // A DEAD TOKEN MUST NOT LOOK LIKE A LIVE ONE. Sessions expire after 30
    // days and can be revoked server-side, and until now the expired token
    // stayed in localStorage — so isSignedIn() kept answering true, guarded
    // screens kept rendering, and every write failed 401 with no explanation.
    if (!user && backend().auth.token()) {
      try {
        await backend().auth.logout()
      } catch {
        /* already gone server-side; the local copy is what mattered */
      }
    }
    return user
  },
  async logout(): Promise<void> {
    await backend().auth.logout()
  },
  /**
   * Email a password reset link.
   *
   * Always resolves with the same message whether or not the address has an
   * account — otherwise this becomes a way to test who is registered.
   * `returnTo` is where the link should land; the token arrives as
   * ?nova_reset=... on that URL.
   */
  async requestPasswordReset(email: string, returnTo?: string): Promise<string> {
    return await backend().auth.requestPasswordReset(email, returnTo)
  },
  /** Spend a reset token, set the new password, and sign in. */
  async confirmPasswordReset(token: string, password: string): Promise<NovaUser> {
    return await backend().auth.confirmPasswordReset(token, password)
  },
  /** True if a session token is stored. Does not verify it with the server. */
  isSignedIn(): boolean {
    try {
      return Boolean(backend().auth.token())
    } catch {
      return false
    }
  },
}

/**
 * What a connector call answers.
 *
 * NOTHING IN `connectors` THROWS, and that is deliberate. A connector is the
 * one part of this app somebody else can switch off — the owner disconnects
 * Shopify from the Nova panel and no rebuild happens — so that arrives as a
 * value to branch on rather than an exception that blanks a page.
 *
 * `status` carries the reason: 409 the owner has not connected (or has
 * disconnected) the service, 403 the write grant was never given, 404 no such
 * connector or resource, 0 the network. Render your own content on any of
 * them; a page that shows nothing because a provider was slow is broken.
 */
export interface ConnectorResult<T = any> {
  ok: boolean
  status: number
  data: T | null
  error: string
}

/**
 * Outside services the owner connected, read through Nova.
 *
 * Nova holds every credential server-side and calls the provider for you, so
 * this app never sees a key, never asks anyone for one, and never calls a
 * provider directly.
 *
 *   const r = await connectors.read<{ products: Product[] }>(
 *     'shopify', 'products', { limit: 24 })
 *   if (r.ok) setProducts(r.data!.products)
 *   else setProducts(DEMO_PRODUCTS)
 *
 * What each connector exposes is stated in the build prompt. Nothing is
 * assumed here — this file names no provider.
 */
export const connectors = {
  /** What is connected right now, and what each may be asked for. */
  async list(): Promise<ConnectorResult<{ connectors: Record<string, any> }>> {
    return await backend().connectors.list()
  },
  /** A public read, cached and rate-limited on the server. */
  async read<T = any>(
    connectorId: string,
    resource: string,
    params: Record<string, string | number | boolean> = {}
  ): Promise<ConnectorResult<T>> {
    return await backend().connectors.read(connectorId, resource, params)
  },
  /**
   * Something happening in the owner's account — starting a checkout, say.
   * Needs the owner's separate write grant and answers `status: 403` without
   * it, so check `ok` before showing a success state.
   */
  async action<T = any>(
    connectorId: string,
    name: string,
    body: Record<string, any> = {}
  ): Promise<ConnectorResult<T>> {
    return await backend().connectors.action(connectorId, name, body)
  },
}

/**
 * A collection, loaded and kept in state.
 *
 * `reload` is returned rather than the hook watching for changes: writes go
 * through db.* and the caller knows exactly when it changed, which is simpler
 * and cheaper than polling.
 */
export function useCollection<T>(collection: string, options: QueryOptions = {}) {
  const [rows, setRows] = useState<NovaRecord<T>[]>([])
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const key = JSON.stringify(options)

  const reload = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const res = await db.list<T>(collection, JSON.parse(key))
      setRows(res.records)
      setTotal(res.total)
    } catch (e: any) {
      setError(e?.message || 'Could not load data')
    } finally {
      setLoading(false)
    }
  }, [collection, key])

  useEffect(() => {
    let cancelled = false
    ;(async () => {
      await reload()
      if (cancelled) return
    })()
    return () => {
      cancelled = true
    }
  }, [reload])

  return { rows, total, loading, error, reload }
}

/** The signed-in user, or null while loading / signed out. */
export function useUser() {
  const [user, setUser] = useState<NovaUser | null>(null)
  const [loading, setLoading] = useState(true)

  const refresh = useCallback(async () => {
    setLoading(true)
    try {
      setUser(await auth.me())
    } catch {
      setUser(null)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void refresh()
  }, [refresh])

  return { user, loading, refresh }
}
