// src/lib/nova-auth.tsx — drop-in sign-in for this app.
//
// Generated by Nova. Two components, no configuration:
//
//   <RequireAuth><Dashboard /></RequireAuth>   // gate a page
//   <NovaAuth onSignedIn={u => ...} />         // the panel on its own
//
// Accounts are real and belong to THIS app only. Rows written while signed in
// belong to that user — pass { mine: true } to a query to read only theirs.
import { useState, type FormEvent, type ReactNode } from 'react'
import { auth, useUser, type NovaUser } from './nova'

export interface NovaAuthProps {
  /** Called once sign-in or sign-up succeeds. */
  onSignedIn?: (user: NovaUser) => void
  /** Heading above the form. */
  title?: string
  /** Line under the heading. */
  subtitle?: string
  /** Any CSS colour — the button, links and focus ring follow it. */
  accent?: string
  /** Start on the sign-up tab instead of sign-in. */
  defaultMode?: 'signin' | 'signup'
}

export function NovaAuth({
  onSignedIn,
  title = 'Sign in',
  subtitle = 'Use your email and a password.',
  accent = '#2563eb',
  defaultMode = 'signin',
}: NovaAuthProps) {
  const [mode, setMode] = useState<'signin' | 'signup' | 'reset'>(defaultMode)
  const [notice, setNotice] = useState<string | null>(null)
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [name, setName] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const signingUp = mode === 'signup'
  const resetting = mode === 'reset'

  // The token arrives on the URL the reset email pointed at. Reading it here
  // means an app needs no route of its own to complete a reset.
  const resetToken =
    typeof window !== 'undefined'
      ? new URLSearchParams(window.location.search).get('nova_reset') || ''
      : ''

  async function submit(e: FormEvent) {
    e.preventDefault()
    if (busy) return
    setError(null)
    // Checked here as well as on the server so the common mistakes are
    // answered instantly instead of costing a round trip.
    if (!resetting || !resetToken) {
      if (!email.includes('@')) return setError('Enter a valid email address.')
    }
    if (!(resetting && !resetToken) && password.length < 8) {
      return setError('Password must be at least 8 characters.')
    }
    setBusy(true)
    try {
      if (resetting && !resetToken) {
        // WHERE THE EMAILED LINK SHOULD LAND: the address the visitor can see.
        // A published app runs inside the frame its site shell provides, so
        // window.location.href here is the internal asset URL — a link back to
        // it works but shows a visitor a URL that is not their site. The top
        // URL is the real one, readable now that the frame shares the site's
        // origin, and the frame's own URL remains the fallback.
        let returnTo = window.location.href
        try {
          if (window.top && window.top !== window.self && window.top.location.href) {
            returnTo = window.top.location.href
          }
        } catch {
          /* cross-origin top — the frame's own URL is the right answer */
        }
        setNotice(await auth.requestPasswordReset(email, returnTo))
        return
      }
      const user = resetting
        ? await auth.confirmPasswordReset(resetToken, password)
        : signingUp
          ? await auth.signup(email, password, name || undefined)
          : await auth.login(email, password)
      onSignedIn?.(user)
    } catch (err: any) {
      setError(err?.message
        || (resetting ? 'Could not reset that password.'
            : signingUp ? 'Could not create that account.' : 'Could not sign in.'))
    } finally {
      setBusy(false)
    }
  }

  const field: React.CSSProperties = {
    width: '100%', boxSizing: 'border-box', padding: '10px 12px',
    borderRadius: 10, border: '1px solid rgba(128,128,128,0.35)',
    background: 'transparent', color: 'inherit', font: 'inherit', outline: 'none',
  }
  const tab = (active: boolean): React.CSSProperties => ({
    flex: 1, padding: '8px 0', cursor: 'pointer', font: 'inherit',
    fontWeight: 600, fontSize: 13, background: 'transparent', border: 'none',
    color: active ? accent : 'inherit', opacity: active ? 1 : 0.55,
    borderBottom: active ? `2px solid ${accent}` : '2px solid transparent',
  })

  return (
    <div style={{
      maxWidth: 380, width: '100%', margin: '0 auto', padding: 24,
      borderRadius: 16, border: '1px solid rgba(128,128,128,0.22)',
      display: 'grid', gap: 14, color: 'inherit',
    }}>
      <div style={{ display: 'flex', gap: 8 }}>
        <button type="button" style={tab(!signingUp)} onClick={() => { setMode('signin'); setError(null) }}>
          Sign in
        </button>
        <button type="button" style={tab(signingUp)} onClick={() => { setMode('signup'); setError(null) }}>
          Create account
        </button>
      </div>

      <div>
        <h2 style={{ margin: 0, fontSize: 20, fontWeight: 700 }}>
          {resetting ? (resetToken ? 'Choose a new password' : 'Reset your password')
            : signingUp ? 'Create your account' : title}
        </h2>
        <p style={{ margin: '6px 0 0', fontSize: 13, opacity: 0.7 }}>
          {resetting
            ? (resetToken
                ? 'Pick something you have not used before.'
                : "Enter your email and we'll send you a link.")
            : subtitle}
        </p>
      </div>

      {!resetting && <button type="button" disabled={busy} onClick={async () => {
        setError(null); setBusy(true)
        try { onSignedIn?.(await auth.signInWithNova()) }
        catch (err: any) { setError(err?.message || 'Could not sign in with Nova.') }
        finally { setBusy(false) }
      }} style={{
        display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 8,
        padding: '11px 14px', borderRadius: 10, cursor: busy ? 'default' : 'pointer',
        border: '1px solid rgba(128,128,128,0.35)', background: 'transparent',
        color: 'inherit', font: 'inherit', fontWeight: 600, opacity: busy ? 0.65 : 1,
      }}>
        <span aria-hidden style={{
          width: 16, height: 16, borderRadius: '50%',
          border: `2px solid ${accent}`, borderTopColor: 'transparent',
          display: 'inline-block',
        }} />
        Continue with Nova
      </button>}

      {!resetting && (
        <div style={{ display: 'flex', alignItems: 'center', gap: 10, opacity: 0.45 }}>
          <span style={{ flex: 1, height: 1, background: 'currentColor' }} />
          <span style={{ fontSize: 11, letterSpacing: '0.06em' }}>OR</span>
          <span style={{ flex: 1, height: 1, background: 'currentColor' }} />
        </div>
      )}

      <form onSubmit={submit} style={{ display: 'grid', gap: 10 }}>
        {signingUp && (
          <input style={field} placeholder="Your name (optional)" value={name}
                 onChange={e => setName(e.target.value)} autoComplete="name" />
        )}
        {!(resetting && resetToken) && (
          <input style={field} type="email" placeholder="you@example.com" value={email} required
                 onChange={e => setEmail(e.target.value)} autoComplete="email" />
        )}
        {!(resetting && !resetToken) && (
          <input style={field} type="password"
                 placeholder={resetting ? 'New password' : 'Password'}
                 value={password} required
                 onChange={e => setPassword(e.target.value)}
                 autoComplete={signingUp || resetting ? 'new-password' : 'current-password'} />
        )}

        {error && (
          <p role="alert" style={{ margin: 0, fontSize: 13, color: '#dc2626' }}>{error}</p>
        )}
        {notice && (
          <p role="status" style={{ margin: 0, fontSize: 13, opacity: 0.8 }}>{notice}</p>
        )}

        <button type="submit" disabled={busy} style={{
          padding: '11px 14px', borderRadius: 10, border: 'none', cursor: busy ? 'default' : 'pointer',
          background: accent, color: '#fff', font: 'inherit', fontWeight: 600,
          opacity: busy ? 0.65 : 1,
        }}>
          {busy ? 'Just a moment…'
            : resetting ? (resetToken ? 'Set new password' : 'Email me a link')
            : signingUp ? 'Create account' : 'Sign in'}
        </button>

        {!signingUp && (
          <button type="button" onClick={() => {
            setError(null); setNotice(null)
            setMode(resetting ? 'signin' : 'reset')
          }} style={{
            background: 'none', border: 'none', padding: 0, cursor: 'pointer',
            font: 'inherit', fontSize: 12, color: accent, opacity: 0.9,
            justifySelf: 'start',
          }}>
            {resetting ? 'Back to sign in' : 'Forgot your password?'}
          </button>
        )}
      </form>
    </div>
  )
}

export interface RequireAuthProps {
  children: ReactNode
  /** Shown while the session is being checked. */
  fallback?: ReactNode
  accent?: string
  title?: string
  subtitle?: string
}

/**
 * Renders `children` only to a signed-in user, and the sign-in panel to
 * everyone else. The whole of route protection, in one component.
 */
export function RequireAuth({ children, fallback, accent, title, subtitle }: RequireAuthProps) {
  const { user, loading, refresh } = useUser()

  if (loading) {
    return <>{fallback ?? <div style={{ padding: 32, textAlign: 'center', opacity: 0.6 }}>Loading…</div>}</>
  }
  if (!user) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', padding: '48px 20px' }}>
        <NovaAuth accent={accent} title={title} subtitle={subtitle} onSignedIn={() => void refresh()} />
      </div>
    )
  }
  return <>{children}</>
}
