// src/animations.ts — GENERATED BY NOVA. Do not hand-edit.
// Motion for this build, seeded on the brand — the export names are fixed and
// every component imports them by hand; only the values below vary.
import type { Variants, Transition } from "framer-motion";

// === SPRING CONFIGS ===
export const spring = {
  gentle: { type: "spring", stiffness: 109, damping: 20 } as Transition,
  snappy: { type: "spring", stiffness: 254, damping: 20 } as Transition,
  bouncy: { type: "spring", stiffness: 426, damping: 10 } as Transition,
  slow: { type: "spring", stiffness: 71, damping: 27 } as Transition,
};

// === EASING ===
export const ease = {
  smooth: [0.25, 0.46, 0.45, 0.94] as const,
  snappy: [0.34, 1.56, 0.64, 1] as const,
  cinematic: [0.83, 0, 0.17, 1] as const,
};

// === DIRECTIONAL FADES ===
export const fadeUp: Variants = {
  hidden: { opacity: 0, y: 45 },
  show: { opacity: 1, y: 0, transition: { duration: 0.51, ease: ease.smooth } },
};
export const fadeDown: Variants = {
  hidden: { opacity: 0, y: -37 },
  show: { opacity: 1, y: 0, transition: { duration: 0.54, ease: ease.smooth } },
};
export const fadeLeft: Variants = {
  hidden: { opacity: 0, x: -47 },
  show: { opacity: 1, x: 0, transition: { duration: 0.56, ease: ease.smooth } },
};
export const fadeRight: Variants = {
  hidden: { opacity: 0, x: 53 },
  show: { opacity: 1, x: 0, transition: { duration: 0.54, ease: ease.smooth } },
};
export const scaleIn: Variants = {
  hidden: { opacity: 0, scale: 0.81 },
  show: { opacity: 1, scale: 1, transition: spring.gentle },
};

// === STAGGER FACTORY ===
export const stagger = (
  delayChildren = 0.08,
  staggerChildren = 0.09,
): Variants => ({
  hidden: { opacity: 0 },
  show: { opacity: 1, transition: { delayChildren, staggerChildren } },
});

// === HERO SECTION ===
export const heroContainer: Variants = {
  hidden: {},
  show: { transition: { staggerChildren: 0.09, delayChildren: 0.22 } },
};
export const heroItem: Variants = {
  hidden: { opacity: 0, y: 63, filter: "blur(8px)" },
  show: {
    opacity: 1,
    y: 0,
    filter: "blur(0px)",
    transition: { duration: 0.77, ease: ease.smooth },
  },
};

// === PAGE TRANSITIONS ===
export const pageTransition: Variants = {
  initial: { opacity: 0, y: 12 },
  animate: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.37, ease: ease.smooth },
  },
  exit: {
    opacity: 0,
    y: -9,
    transition: { duration: 0.31, ease: ease.cinematic },
  },
};

// === HOVER PRESETS ===
export const hoverLift = { y: -3, transition: spring.snappy };
export const hoverScale = { scale: 1.04, transition: spring.snappy };
export const hoverGlow = {
  boxShadow: "0 22px 50px rgba(0,0,0,0.18)",
  transition: { duration: 0.3 },
};

// === ALIASES FOR NAMES MODELS INVENT ===
// Not part of the system — see `_ANIMATION_ALIASES`. A component importing
// `fadeInUp` fails to resolve the module and takes the page down with it, so
// these cost four lines and remove a build failure.
export const fadeInUp = fadeUp;
export const fadeInDown = fadeDown;
export const fadeInLeft = fadeLeft;
export const fadeInRight = fadeRight;
