// src/tokens.ts — GENERATED BY NOVA. Do not hand-edit.
// Colour Option 1 and Typography Option 1
// of the curated design system for: Plant Care Tracker
//
// These are the authoritative values for this build. Import them; never
// re-declare a hex code or a font name in a component.
//
// EACH LINE BELOW IS A PAIR: the first is the foreground that is legible
// on the second. `background`, `surface`, `muted`, `primary`, `secondary`
// and `accent` are SURFACES. Use a surface for `backgroundColor` and its
// partner for `color`.
//   text             goes on  background
//   cardForeground   goes on  surface
//   mutedForeground  goes on  muted
//   onPrimary        goes on  primary
//   onSecondary      goes on  secondary
//   onAccent         goes on  accent
//   onDestructive    goes on  destructive
//
// AN `on<Role>` IS THE FOREGROUND *FOR* THAT ROLE, NOT A SHADE OF IT.
// `onAccent` is what is legible on `accent`; it is not accent-coloured
// text. `mutedForeground` is what is legible on `muted`, not a dimmer
// `text`. Off its own surface an `on<Role>` is usually the worst colour
// on the page — measured, a `#000000` onAccent eyebrow on a `#131210`
// primary section at 1.12:1, on seven files of one delivered build.
//
// A TINTED LABEL IS ALLOWED, AND THIS IS HOW. `primary`, `secondary` and
// `accent` may be a `color` — but only where they clear 4.5:1 against the
// surface that text lands on, which is usually the light ones and almost
// never a coloured section. NAME THE SURFACE FIRST, THEN PICK THE COLOUR.
//
// NEVER `white` OR `black` BY HAND. Across the same builds that is 46
// pieces of text and 14 of them are unreadable — the worst rate of the
// three. The pair above is the answer that is already right.
export const tokens = {
  color: {
    white: "#FFFFFF",
    black: "#000000",
    primary: "#147039",
    onPrimary: "#FFFFFF",
    secondary: "#04A079",
    onSecondary: "#000000",
    accent: "#CE7D05",
    onAccent: "#000000",
    background: "#E7FCEE",
    text: "#0F172A",
    surface: "#FFFFFF",
    cardForeground: "#0F172A",
    muted: "#E9F5EE",
    mutedForeground: "#606F85",
    border: "#E2EFE7",
    ring: "#15803D",
    destructive: "#DC2626",
    onDestructive: "#FFFFFF",
  },
  font: {
    heading: "Lora",
    body: "Raleway",
  },
  spacing: {
    section: "pt-20 pb-14 lg:pt-28 lg:pb-20",
    container: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8",
    card: "p-6 lg:p-8",
    gap: "gap-6 lg:gap-8",
  },
  radius: {
    sm: "rounded-lg",
    md: "rounded-xl",
    lg: "rounded-2xl",
    xl: "rounded-3xl",
  },
  shadow: {
    sm: "shadow-md",
    md: "shadow-lg",
    lg: "shadow-xl",
    hover: "shadow-2xl",
  },
  // Selected text. `src/index.css` paints `::selection` with exactly
  // these two, so a component that highlights text by hand matches the
  // page instead of inventing a second answer.
  selection: {
    background: "#CE7D05",
    text: "#000000",
  },
} as const;
